name: Code check
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: joelvaneenwyk/gh-actions-lua@main
        with:
          luaVersion: "5.2.4"
      - uses: joelvaneenwyk/gh-actions-luarocks@main
      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install cluacov
          luarocks install luacheck
      - name: Run checks
        run: |
          luacheck .
